### PR TITLE
Fix a few makefile issues

### PR DESCRIPTION
**Pull request by ximion**
The MODEL hardcoding breaks builds on pretty much any architecture that isn't amd64 and
ia32.

Removing this explicitness had no bad consequences in Debian, and hardcoding this makes compiling GtkD for multiple architectures impossible (it's also bad practice).

The second commit adds multiarch support, which is primarily useful for Debian. I also only tested this with Debian-based systems, but it should work well for non-Debian-based systems too, since it has a fallback for that case (this whole multiarch solution is a hack, but it's the best idea I came up with to fix this with a hand-written makefile).

### CODE REVIEW

**Comment by MikeWey** [comment]
MODEL is a leftover from when dmd defaulted to building 32bit binaries, even when it was a 64bit dmd on a 64bit os. So that is ok to remove.

I'm not so sure about the other commit, while the pkg-config files should probable move from share to lib since they are not architecture independent. Installing the libraries in lib64 might not be correct on all distributions. On Archlinux for example the 64bit libraries are in /urs/lib/ and i gain an lib32 when installing a multilib version.

Looking at how Archlinux builds Gtk they leave to libdir to the default location an only set it to /usr/lib32 for the multilib version. I couldn't find the same for Debian but if the makefiles for GTK default to lib on 64bit we should probably stick to that.

**Comment by ximion** [comment]
If the pkgconfig files are arch-dependent, they actually must be placed in `/usr/lib`, so that is definitely the right thing to do.

I updated the patch to not install into `/usr/lib64` on non-Debian amd64 architectures.

**Comment by MikeWey** [comment]
Ideally i don't want to do anything distribution specific in the Makefile.
So we want the pick a sane default either lib or lib64 and let 
distributions that use a different location use libpath to override it.
The question is what are other libraries/makefiles doing, because we 
want something standard/de facto standard.

**Comment by ximion** [comment]
Previously, it wasn't possible to override any install path because the makefile was overriding variables - with the `?=` operator, it will now only set the path when it hasn't been defined already.

As for picking a default: There is none.
On Debian, libraries must be installed into `/usr/lib/<triplet>` to have multiarch support (e.g. `/usr/lib/y86_64-linux-gnu`).
On Fedora it's `/usr/lib<suffix>` instead, e.g. `/usr/lib64` (unless it's a ia32 machine).
Apparently, Archlinux doesn't care and always uses `/usr/lib`.

To make this work properly, you could use a system like CMake or Automake, which knows about distro specific paths. If you only have a hand-written makefile, you can try to catch as many distros as possible, and have the others override the path or provide a patch.

**Comment by MikeWey** [comment]
prefix, libdir and datadir were meant to be overridden, so they should 
indeed be using ?=.

**Pull request merged**
