### PR TITLE
Update version to 3.8.4

### PR DESCRIPTION
**Pull request by gnunn1**

### CODE REVIEW

**Comment by gnunn1** [comment]
This is to fix #259 to support a release of tilix, I believe this is the right spot to to fix the library name.

**Comment by MikeWey** [comment]
Thanks, should we now release 3.8.5 (with the version updated) to get the correct library version in a release?

**Comment by jbicha** [comment]
@MikeWey That makes sense to me :+1:

**Comment by gnunn1** [comment]
It's fine with me as well, I'll cut a new Tilix release to reference 3.8.5 when available.

**Comment by MikeWey** [comment]
3.8.5 is released.

**Pull request merged**
